import "../styles/globals.css";

export const metadata = {
  title: "Next.js App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="kr">
      <body>{children}</body>
    </html>
  );
}
